config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "movies#index"
  get 'search-movie' => 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, after_add: :update_average_rating, after_remove: :update_average_rating

  validates :description, :director, presence: true
  validates :name, uniqueness: true
  validate :validate_year

  scope :query_movie, ->(query:) { includes(reviews: :user).where('lower(name) LIKE lower(:search)', search: "%#{query}%") }

  private

  def update_average_rating(review = nil)
    return self.average_rating = 0.0 unless reviews.present?

    total_rating = reviews.sum(:star_rating)
    average_rating = total_rating / reviews.size.to_f
    self.update_attribute(:average_rating, average_rating)
  end

  def validate_year
    self.errors.add(:base, "Year should be between 1900 and current year") unless (1900..Date.today.year).include? year.to_i
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :star_rating, presence: true, inclusion: { in: 1..5, message: "should be between 1 and 5" }
  validates :user_id, uniqueness: { scope: [:movie_id], message: "already rated this movie!" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = if params[:query]
                search_movie
                 else
                   Movie.includes(reviews: :user).order(created_at: :asc)
                 end
  end

  private

  def search_movie
    Movie.query_movie(query: params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def display_movie_attributes(model_attribute, locator)
    model_attribute.map {|attr| attr[locator]}.join(', ')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div>
	<h1 class="text-center">Movie Overview</h1>
	<div class="d-flex justify-content-between mb-3">
		<div class="col-12 mb-5">
			<%= form_with url: search_movie_path, method: :get, local: true, class: "form-inline search-form" do |f| %>
				<%= f.text_field :query, value: params[:query], class: "form-control mr-sm-2 search-query", placeholder: "Search Movie Name" %>
			<% end %>
		</div>
	</div>
	<div class="d-flex">
	<% if @movies.present? %>
			<%  @movies.each do |movie| %>
				<div class="card mr-3" style="width: 18rem;">
					<div class="card-body">
						<h5 class="card-title"><%= movie.name %></h5>
						<h6 class="card-subtitle mb-2 text-muted"><%= movie.year %></h6>
						<p class="card-text truncate-text"><%= movie.description %></p>
						<p class="card-text"><span>Actors: </span><%= display_movie_attributes(movie.actors, "actor") %></p>
						<p class="card-text">Locations: <%= display_movie_attributes(movie.filming_locations, "locator") %></p>
						<p class="card-text">Countries: <%= display_movie_attributes(movie.countries, "country") %></p>
						<p class="card-text">Average rating: <%= movie.average_rating %></p>
					</div>
				</div>
			<% end %>
		<% else %>
		<p>There are no movies currently</p>
		<% end %>
	</div>
</div>